# ???????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.33.210.228:3306/author_plat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: author_plat
    password: F6FWtzj6wybwyJG4

# MybatisPlus ????
mybatis-plus:
  configuration:
    # ??????
    map-underscore-to-camel-case: true

