
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    时区为东八区,开启useAffectedRows=true保证update返回影响行数
    url: jdbc:mysql://101.33.210.228:3306/author_plat?useUnicode=true&characterEncoding=utf-8&useSSL=false&timeZone=GMT%2B8&useAffectedRows=true
    username: author_plat
    password: F6FWtzj6wybwyJG4
  data:
    redis:
      host: guico.top
      password: 411326li

  mail:
    host: smtp.163.com
    username: a1305487489@163.com
    password: NFMHYYIEAUXHTWLP
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
            auth: true
            ssl:
                enable: true
                trust: smtp.163.com
            starttls:
                enable: true
                required: true



sa-token:
  roles: admin, root, normal
  activity-timeout: 300000
  is-concurrent: false
  token-style: simple-uuid
  jwt-secret-key: lkuiantlasoinmr


server:
  port: 8081
  servlet:
    session:
      timeout: 10800




